In [ ]:
from pyscf import gto, scf, mp, cc

# a = 2 # bond length in a cluster
# d = 2.2 # distance between each cluster
# unit = 'b' # unit of length
# na = 2  # size of a cluster (monomer)
# nc = 4 # set as integer multiple of monomers
# spin = 0 # spin per monomer
# frozen = 0 # frozen orbital per monomer
# elmt = 'H'
# basis = '6-31g'
# atoms = ""
# for n in range(nc*na):
#     shift = ((n - n % na) // na) * (d-a)
#     atoms += f"{elmt} {n*a+shift:.5f} 0.00000 0.00000 \n"

atoms = '''
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000
O   1.350625   0.111469   0.000000
H   1.680398  -0.373741  -0.758561
H   1.680398  -0.373741   0.758561
'''
basis = 'ccpvdz'

mol = gto.M(atom=atoms, basis=basis, spin=0, verbose=4, max_memory=16000)
mf = scf.UHF(mol).density_fit()
mf.kernel()

mo, _ = mf.stability()
dm = mf.make_rdm1(mo,mf.mo_occ)
mf.kernel(dm0=dm)
mo, _ = mf.stability()
dm = mf.make_rdm1(mo,mf.mo_occ)
mf.kernel(dm0=dm)
mo, _ = mf.stability()

System: uname_result(system='Linux', node='yichi-thinkpad', release='4.4.0-26100-Microsoft', version='#7309-Microsoft Fri Jan 01 08:00:00 PST 2016', machine='x86_64')  Threads 12
Python 3.10.16 | packaged by conda-forge | (main, Dec  5 2024, 14:16:10) [GCC 13.3.0]
numpy 1.24.3  scipy 1.14.1  h5py 3.12.1
Date: Sat Dec 20 20:51:23 2025
PySCF version 2.8.0
PySCF path  /home/yichi/research/software/lno_pyscf
GIT HEAD (branch master) ef75f4190e4de208685670651dc6c467f72b6794

[ENV] PYSCF_EXT_PATH /home/yichi/research/software/pyscf
[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 8
[INPUT] num. electrons = 8
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 H      0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.00

SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = False
chkfile to save SCF result = /tmp/tmpek6mwffb
max_memory 16000 MB (current use 157 MB)
number electrons alpha = 4  beta = 4
Set gradient conv threshold to 3.16228e-05
******** <class 'pyscf.df.df.DF'> ********
auxbasis = None
max_memory = 16000
Default auxbasis cc-pvdz-jkfit is used for H 6-31g
init E= -2.59982415710191
  alpha nocc = 4  HOMO = -0.222117200322356  LUMO = -0.151102795004154
  beta  nocc = 4  HOMO = -0.218758808152252  LUMO = -0.149591369689582
cycle= 1 E= -3.66028644369393  delta_E= -1.06  |g|= 0.0551  |ddm|= 1.15
  alpha nocc = 4  HOMO = -0.325628847155423  LUMO = -0.10502070027261
  beta  nocc = 4  HOMO = -0.32664374004323  LUMO = -0.104884018105618
cycle= 2 E= -3.67086619943439  delta_E= -0.0106  |g|= 0.0245  |ddm|= 0.149
  alpha nocc = 4  HOMO = -0.340512605916626  LUMO = -0.0954107123455438
  beta  nocc = 4  HOMO = -0.341341419380762  LUMO = -0.0958261307884662
cycle= 3 E= -3.67426

In [19]:
from pyscf import lo
import numpy as np
nfrozen = 0
orbocca = mf.mo_coeff[0][:,nfrozen:np.count_nonzero(mf.mo_occ[0])]
orboccb = mf.mo_coeff[1][:,nfrozen:np.count_nonzero(mf.mo_occ[1])]

loc_a = lo.PM(mol, orbocca)
orbloca = loc_a.kernel()
stable_a, orbloca = loc_a.stability_jacobi()

loc_b = lo.PM(mol, orboccb)
orblocb = loc_b.kernel()
stable_b, orblocb = loc_b.stability_jacobi()

print(f'local orbital stability: {stable_a}, {stable_b}')

lo_coeff = [orbloca, orblocb]



******** <class 'pyscf.lo.pipek.PipekMezey'> ********
conv_tol = 1e-06
conv_tol_grad = None
max_cycle = 100
max_stepsize = 0.05
max_iters = 20
kf_interval = 5
kf_trust_region = 5
ah_start_tol = 1000000000.0
ah_start_cycle = 1
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_max_cycle = 40
ah_trust_region = 3
init_guess = atomic
pop_method = meta_lowdin
Set conv_tol_grad to 0.000316228
macro= 1  f(x)= 8.6131010783688  delta_f= 8.6131  |g|= 0.00104762  1 KF 1 Hx
macro= 2  f(x)= 8.6131010783688  delta_f= 0  |g|= 4.98968e-06  1 KF 1 Hx
macro X = 2  f(x)= 8.6131010783688  |g|= 4.98968e-06  4 intor 2 KF 2 Hx


******** <class 'pyscf.lo.pipek.PipekMezey'> ********
conv_tol = 1e-06
conv_tol_grad = None
max_cycle = 100
max_stepsize = 0.05
max_iters = 20
kf_interval = 5
kf_trust_region = 5
ah_start_tol = 1000000000.0
ah_start_cycle = 1
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_max_cycle = 40
ah_trust_region = 3
init_guess = atomic
pop_method = meta_lowdin
Set conv_

In [24]:
mycc = cc.CCSD(mf)
eccsd = mycc.kernel()


******** <class 'pyscf.cc.dfuccsd.UCCSD'> ********
CC2 = 0
CCSD nocc = (4, 4), nmo = (16, 16)
max_cycle = 50
direct = 0
conv_tol = 1e-07
conv_tol_normt = 1e-06
diis_space = 6
diis_start_cycle = 0
diis_start_energy_diff = 1e+09
max_memory 16000 MB (current use 160 MB)
Init t2, MP2 energy = -0.00361386867649878
Init E_corr(UCCSD) = -0.00361386867651366
cycle = 1  E_corr(UCCSD) = -0.00511989831369049  dE = -0.00150602964  norm(t1,t2) = 0.0301452
cycle = 2  E_corr(UCCSD) = -0.00619673848703406  dE = -0.00107684017  norm(t1,t2) = 0.0270852
cycle = 3  E_corr(UCCSD) = -0.00963980609097623  dE = -0.0034430676  norm(t1,t2) = 0.0254551
cycle = 4  E_corr(UCCSD) = -0.0165596786784042  dE = -0.00691987259  norm(t1,t2) = 0.0225108
cycle = 5  E_corr(UCCSD) = -0.0343497751486246  dE = -0.0177900965  norm(t1,t2) = 0.018121
cycle = 6  E_corr(UCCSD) = -0.0333607271159406  dE = 0.000989048033  norm(t1,t2) = 0.0131056
cycle = 7  E_corr(UCCSD) = -0.035019041392358  dE = -0.00165831428  norm(t1,t2) = 0.0117

In [25]:
t2aa, t2ab, t2bb = mycc.t2

In [83]:
t2_test = t2aa.transpose(0,2,1,3)
ni,na,_,_ = t2_test.shape
t2_test = t2_test.reshape(ni*na,ni*na)
print(t2_test.shape)

(48, 48)


In [86]:
t2_test.max()

0.00423241956989624

In [84]:
print(t2_test - t2_test.T)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [40]:
import numpy as np
u,s,v = np.linalg.svd(t2_test)
print(u.shape)
print(s.shape)
print(v.shape)

(48, 48)
(48,)
(48, 48)


In [39]:
Sigma = np.zeros((u.shape[1], v.shape[0]))
np.fill_diagonal(Sigma, s)
t2_rec = u @ Sigma @ v
print(abs((t2_rec-t2_test)).max())

2.3671381948588648e-17


In [37]:
t2_l = u.reshape(ni,na,-1)
t2_l = t2_l.transpose(2,0,1)
print(t2_l.shape)

(48, 4, 12)


In [42]:
t2_r = v.reshape(-1,ni,na)
print(t2_r.shape)

(48, 4, 12)


In [44]:
from pyscf import lib
t2_rec = lib.einsum('kia,ljb,kl->iajb',t2_l,t2_r,Sigma)
print(abs((t2_rec-t2aa.transpose(0,2,1,3))).max())

2.3671381948588648e-17


In [47]:
mask_singular = s > 1e-5
s_cut = s[mask_singular]
t2_l_cut = t2_l[mask_singular,:,:]
t2_r_cut = t2_r[mask_singular,:,:]
print(s_cut.shape)
print(t2_l_cut.shape)
print(t2_r_cut.shape)

(34,)
(34, 4, 12)
(34, 4, 12)


In [54]:
t2_l_cut = lib.einsum('kia,k->kia', t2_l_cut, np.sqrt(s_cut))
t2_r_cut = lib.einsum('kia,k->kia', t2_r_cut, np.sqrt(s_cut))

In [ ]:
t2_rec = lib.einsum('kia,kjb->iajb',t2_l_cut,t2_r_cut)
print(abs((t2_rec-t2aa.transpose(0,2,1,3))).max())

1.1964155667284763e-06


In [62]:
def decomp_t2(t2, cutoff=1e-5):
    '''
    t2 shape (i,a,j,b)
    return t2_left, t2_right
    '''
    ni,na,_,_ = t2.shape
    t2 = t2.reshape(ni*na,ni*na)
    u,s,v = np.linalg.svd(t2)
    t2_l = u.reshape(ni,na,-1)
    t2_l = t2_l.transpose(2,0,1)
    t2_r = v.reshape(-1,ni,na)
    mask_singular = s > cutoff
    s_cut = s[mask_singular]
    t2_l_cut = t2_l[mask_singular,:,:]
    t2_r_cut = t2_r[mask_singular,:,:]
    t2_l_cut = lib.einsum('kia,k->kia', t2_l_cut, np.sqrt(s_cut))
    t2_r_cut = lib.einsum('kia,k->kia', t2_r_cut, np.sqrt(s_cut))
    return t2_l_cut, t2_r_cut

In [76]:
t2_test = t2bb.transpose(0,2,1,3)
t2_l_cut, t2_r_cut = decomp_t2(t2_test,cutoff=1e-5)
print(t2_l_cut.shape)
t2_rec = lib.einsum('kia,kjb->iajb',t2_l_cut,t2_r_cut)
print(abs((t2_rec-t2_test)).max())

(34, 4, 12)
1.1964155316824542e-06


In [82]:
for i in range(t2_l_cut.shape[0]):
    print(abs(t2_l_cut[i]-t2_r_cut[i]).max())

4.163336342344337e-17
0.09038623671146193
0.09669764943992
3.3133218391157016e-15
0.07936750795980926
1.0218537713040099e-15
0.09920984259912785
1.873392933837703e-15
0.06337344523423052
4.683753385137379e-17
0.027267213259653957
8.25294693695966e-16
0.02015415823048227
4.575333167888829e-16
0.013315622939262965
2.9284300678833475e-16
0.012186961481882284
1.3704315460216776e-16
8.673617379884035e-17
0.009058155743297071
9.324138683375338e-17
0.007370274772835139
3.7990444123892075e-16
0.00615430029712284
0.00920208993980934
2.5520763887593167e-16
0.004449259017650319
3.5498676480977265e-15
2.875304161431558e-16
0.004051180186720092
0.005001881703142846
2.0209528495129803e-16
5.833549789058257e-16
0.0052432511598090184
