In [1]:
from functools import partial
from pyscf import gto, scf, cc
import numpy as np
from jax import numpy as jnp
from jax import vmap

def get_oo_vv_ov_vo(nocc,m):
    oo = m[:nocc,:nocc]
    vv = m[nocc:,nocc:]
    ov = m[:nocc,nocc:]
    vo = m[nocc:,:nocc]
    return oo,vv,ov,vo

from jax import config
config.update("jax_enable_x64", True)

print = partial(print, flush=True)

a = 1.5 # 2aB
nH = 6
atoms = ""
for i in range(nH):
    atoms += f"H {i*a:.5f} 0.00000 0.00000 \n"

mol = gto.M(atom=atoms, basis="sto6g", verbose=4)
mol.build()

mf = scf.RHF(mol).density_fit()
# mf.conv_tol_grad = 1e-12
# mf = mf.newton()
e = mf.kernel()

mycc = cc.CCSD(mf)
e = mycc.kernel()

System: uname_result(system='Linux', node='yichi-thinkpad', release='4.4.0-26100-Microsoft', version='#5074-Microsoft Fri Jan 01 08:00:00 PST 2016', machine='x86_64')  Threads 12
Python 3.10.16 | packaged by conda-forge | (main, Dec  5 2024, 14:16:10) [GCC 13.3.0]
numpy 1.24.3  scipy 1.14.1  h5py 3.12.1
Date: Sun Oct  5 19:27:02 2025
PySCF version 2.8.0
PySCF path  /home/yichi/research/software/lno_pyscf
GIT HEAD (branch master) ef75f4190e4de208685670651dc6c467f72b6794

[ENV] PYSCF_EXT_PATH /home/yichi/research/software/pyscf
[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 6
[INPUT] num. electrons = 6
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 H      0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.00

In [ ]:
# s1e = mf.get_ovlp()
# fock = mf.get_fock()
# mo_e, mo_c = mf.eig(fock, s1e)
# print(mo_e)
# print(mf.mo_energy)

[-0.45254911 -0.38075758 -0.26784219  0.08948061  0.26115288  0.40958296]
[-0.45254911 -0.38075758 -0.26784219  0.08948061  0.26115288  0.40958296]


In [ ]:
# dm = mf.make_rdm1(mo_c)
# mf.kernel(dm0=dm)



******** <class 'pyscf.df.df_jk.DFRHF'> ********
method = DFRHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
diis_damp = 0
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = False
chkfile to save SCF result = /tmp/tmpwcdwc92c
max_memory 4000 MB (current use 190 MB)
Set gradient conv threshold to 3.16228e-05
init E= -2.75031958695716
  HOMO = -0.267842186506315  LUMO = 0.0894806054712494
cycle= 1 E= -2.75031958695716  delta_E= 2.66e-15  |g|= 5.23e-10  |ddm|= 3.19e-09
  HOMO = -0.267842186373656  LUMO = 0.0894806053834849
Extra cycle  E= -2.75031958695716  delta_E= -8.88e-16  |g|= 2.26e-10  |ddm|= 1.46e-09
converged SCF energy = -2.75031958695716


-2.7503195869571577

In [ ]:
# fock_moc = mo_c.T @ fock @ mo_c
# nocc = np.count_nonzero(mf.mo_occ)
# oo,vv,ov,vo = get_oo_vv_ov_vo(nocc,fock_moc)
# print(vo)

[[-3.36109139e-17  4.72659067e-17  1.79653083e-18]
 [-6.93273911e-17 -6.39598839e-17  7.05642848e-17]
 [ 9.17950898e-17  9.94243535e-17 -1.53835444e-16]]


In [ ]:
# mo = mf.mo_coeff
# fock_mo = mo.T @ fock @ mo
# oo,vv,ov,vo = get_oo_vv_ov_vo(nocc,fock_mo)
# # print(oo)
# # print(vv)
# print(ov)
# # print(vo)

[[ 1.95191227e-16  3.01723230e-10  4.19603476e-16]
 [-5.51205956e-10  5.08448061e-17 -3.21211092e-10]
 [-4.26119368e-16 -4.49730656e-10 -7.09316863e-16]]


In [ ]:
# oo,vv,ov,vo = get_oo_vv_ov_vo(nocc,fock_mo)
# # print(oo)
# # print(vv)
# # print(ov)
# print(vo)

[[ 8.70608783e-17 -1.20482453e-13  3.00577881e-16]
 [ 7.80616843e-14 -3.31049489e-16 -1.26851478e-13]
 [-1.23250736e-16 -8.28966738e-14 -2.29422766e-16]]


In [ ]:
# print(mo_e)
# print(mf.mo_energy)

[-0.45251286 -0.38070639 -0.26774293  0.08946737  0.26118309  0.40967693]
[-0.45251286 -0.38070639 -0.26774293  0.08946737  0.26118309  0.40967693]


In [ ]:
# mo = mf.mo_coeff
# fock = mf.get_fock()
# fock_mo = mo.T @ fock @ mo

In [ ]:
# from pyscf import lo
# nocc = np.count_nonzero(mf.mo_occ)
# lo_occ = lo.Boys(mol,mo_c[:,:nocc]).kernel()
# lo_vir = lo.Boys(mol,mo_c[:,nocc:]).kernel()
# lo_mo = np.hstack((lo_occ,lo_vir))
# dm = mf.make_rdm1(lo_mo)
# mf.kernel(dm0=dm)



******** <class 'pyscf.lo.boys.Boys'> ********
conv_tol = 1e-06
conv_tol_grad = None
max_cycle = 100
max_stepsize = 0.05
max_iters = 20
kf_interval = 5
kf_trust_region = 5
ah_start_tol = 1000000000.0
ah_start_cycle = 1
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_max_cycle = 40
ah_trust_region = 3
init_guess = atomic
Set conv_tol_grad to 0.000316228
macro= 1  f(x)= 30.859906021019  delta_f= 30.8599  |g|= 28.5396  1 KF 3 Hx
macro= 2  f(x)= 30.853859503674  delta_f= -0.00604652  |g|= 2.17103  1 KF 3 Hx
macro= 3  f(x)= 30.853852659843  delta_f= -6.84383e-06  |g|= 0.0295381  1 KF 3 Hx
macro= 4  f(x)= 30.853852659843  delta_f= 4.68958e-13  |g|= 5.70791e-06  1 KF 1 Hx
macro X = 4  f(x)= 30.853852659843  |g|= 5.70791e-06  8 intor 4 KF 10 Hx


******** <class 'pyscf.lo.boys.Boys'> ********
conv_tol = 1e-06
conv_tol_grad = None
max_cycle = 100
max_stepsize = 0.05
max_iters = 20
kf_interval = 5
kf_trust_region = 5
ah_start_tol = 1000000000.0
ah_start_cycle = 1
ah_level_shift = 0

-2.7503195869571577

In [ ]:
# fock_lo = lo_mo.T @ fock @ lo_mo
# oo,vv,ov,vo = get_oo_vv_ov_vo(nocc,fock_lo)
# # print(oo)
# # print(vv)
# # print(ov)
# print(vo)

[[3.64291930e-17 2.08166817e-17 4.16333634e-17]
 [3.46944695e-18 4.16333634e-17 1.66533454e-16]
 [1.38777878e-17 0.00000000e+00 7.63278329e-17]]


In [ ]:
# def mk_1dm(mo,nocc):
#     from pyscf import lib
#     # nocc = np.count_nonzero(occ)
#     dm = 2*mo[:,:nocc] @ mo.T[:nocc,:]
#     # dm = lib.tag_array(dm, mo_coeff=mo, mo_occ=occ)
#     return dm

In [ ]:
# mo_occ = mf.mo_occ
# print(mo[:,:nocc]*mo_occ[mo_occ>0])
# print(mo[:,:nocc]*2)

[[ 0.42624758 -0.79547504  0.89603391]
 [ 0.65917533 -0.89872329  0.54209384]
 [ 0.85376183 -0.2873926  -0.86514968]
 [ 0.85376183  0.2873926  -0.86514968]
 [ 0.65917533  0.89872329  0.54209384]
 [ 0.42624758  0.79547504  0.89603391]]
[[ 0.42624758 -0.79547504  0.89603391]
 [ 0.65917533 -0.89872329  0.54209384]
 [ 0.85376183 -0.2873926  -0.86514968]
 [ 0.85376183  0.2873926  -0.86514968]
 [ 0.65917533  0.89872329  0.54209384]
 [ 0.42624758  0.79547504  0.89603391]]


In [ ]:
# mo = mf.mo_coeff
# mo_dm = mk_1dm(mo,nocc)
# lo_dm = mk_1dm(lo_mo,nocc)
# dm = mf.make_rdm1()
# print(mo_dm)
# print(lo_dm)
# # print(mo_dm-lo_dm)
# print(dm-mo_dm)
# print(dm-lo_dm)

[[ 0.80867216  0.74080915 -0.09133795 -0.31995159  0.0258972   0.17589162]
 [ 0.74080915  0.7680407   0.17603642 -0.08225    -0.03966286  0.0258972 ]
 [-0.09133795  0.17603642  0.77999387  0.69739936 -0.08225    -0.31995159]
 [-0.31995159 -0.08225     0.69739936  0.77999387  0.17603642 -0.09133795]
 [ 0.0258972  -0.03966286 -0.08225     0.17603642  0.7680407   0.74080915]
 [ 0.17589162  0.0258972  -0.31995159 -0.09133795  0.74080915  0.80867216]]
[[ 0.80867216  0.74080915 -0.09133795 -0.31995159  0.0258972   0.17589162]
 [ 0.74080915  0.7680407   0.17603642 -0.08225    -0.03966286  0.0258972 ]
 [-0.09133795  0.17603642  0.77999387  0.69739936 -0.08225    -0.31995159]
 [-0.31995159 -0.08225     0.69739936  0.77999387  0.17603642 -0.09133795]
 [ 0.0258972  -0.03966286 -0.08225     0.17603642  0.7680407   0.74080915]
 [ 0.17589162  0.0258972  -0.31995159 -0.09133795  0.74080915  0.80867216]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 

In [ ]:
# def thouless_trans(t1):
#     # U, s, V = np.linalg.svd(t1.T)
#     # S = np.zeros_like(t1.T, dtype=float)
#     # np.fill_diagonal(S, s)
#     # u_ai = U@S
#     # u_ji = V.T
#     Q, R = np.linalg.qr(t1)
#     u_ai = R.T
#     u_ji = Q
#     u = np.vstack((u_ji,u_ai))
#     return u

In [ ]:
def thouless_trans(t1):
    q, r = np.linalg.qr(t1)
    u_ai = r.T
    u_ji = q
    u_occ = np.vstack((u_ji,u_ai))
    u, _, _ = np.linalg.svd(u_occ)
    return u
u = thouless_trans(10*mycc.t1)
mo_t = mf.mo_coeff @ u
mf.mo_coeff = mo_t

In [52]:
t2_0 = np.zeros(mycc.t2.shape)
eris = mycc.ao2mo(mycc.mo_coeff)
eccsd = mycc.energy(10*mycc.t1, t2_0, eris)
ecc_t2_0 = eccsd+mf.e_tot
print(ecc_t2_0,eccsd)

-2.7500806685523083 0.0002389184048477652


In [ ]:
# def rhf_olp(rhf1,rhf2):
#     '''<rhf1|rhf2>'''
#     olp = jnp.linalg.det(rhf1.T.conj() @ rhf2) ** 2
#     return olp

In [ ]:
# hcore = mf.get_hcore()
# mo = mf.mo_coeff
# # h1e_mo = np.dot(mo.T,np.dot( hcore, mo))
# h1e_mo = mo.T @ hcore @ mo
# print(h1e_mo)
# ham_data['h1']-h1e_mo

[[-1.39494247e+00 -1.52655666e-16  1.18481321e-01  4.44089210e-16]
 [-7.45931095e-17 -1.23539794e+00  0.00000000e+00 -9.29652546e-02]
 [ 1.18481321e-01  5.55111512e-17 -1.09350707e+00  1.52655666e-16]
 [ 1.66533454e-16 -9.29652546e-02  3.81639165e-16 -1.00930479e+00]]


In [ ]:
# chol = ham_data['chol']
# nao = ham_data['h1'].shape[-1]
# chol = chol.reshape((-1, nao, nao))
# print(chol.shape)
# eris_chol = jnp.einsum('gpr,gqs->prqs',chol,chol,optimize='optimal')
# print(eris_chol.shape)

(10, 4, 4)
(4, 4, 4, 4)


In [ ]:
# from pyscf import ao2mo
# from ad_afqmc import pyscf_interface
# eri_mo = ao2mo.kernel(mf.mol,mf.mo_coeff,compact=False)
# chol = pyscf_interface.modified_cholesky(eri_mo,max_error=chol_cut)

In [ ]:
# eri_mo = ao2mo.incore.full(mol.intor('int2e'), mf.mo_coeff)
# eri_mo = ao2mo.restore(1, eri_mo, mol.nao_nr())
# # eri_mo = eri_mo.reshape((nao, nao, nao, nao))
# print(eri_mo.shape)

(4, 4, 4, 4)


In [ ]:
# print(np.max(eri_mo-eris_chol))

1.5922312936410939e-16


In [41]:
options = {'n_eql': 4,
           'n_prop_steps': 10,
            'n_ene_blocks': 1,
            'n_sr_blocks': 10,
            'n_blocks': 10,
            'n_walkers': 1,
            'seed': 2,
            'walker_type': 'rhf',
            'trial': 'cisd',
            'dt':0.005,
            'free_projection':False,
            'ad_mode':None,
            'use_gpu': False,
            }

# mf.mo_coeff = mo_c

In [68]:
from pyscf.ci.cisd import CISD
from pyscf.cc.ccsd import CCSD
from pyscf.cc.uccsd import UCCSD
from ad_afqmc.lno.cc import LNOCCSD
from ad_afqmc.lno_afqmc import lno_maker, afqmc_maker, lnoafqmc_runner
from pyscf import ao2mo, mcscf, scf, lib

frozen = None
thresh = 1e-10
lo_type = 'boys'
run_frg_list = [0]
eris = None

mfcc = mf
if isinstance(mfcc, (CCSD, CISD)):
    full_cisd = True
    mf = mfcc._scf
else:
    full_cisd = False
    mf = mfcc

no_type = 'ie' # cim

if isinstance(thresh, list):
    thresh_occ, thresh_vir = thresh
else:
    thresh_occ = thresh*10
    thresh_vir = thresh

lno_cc = LNOCCSD(mf, thresh=thresh, frozen=frozen)
lno_cc.thresh_occ = thresh_occ
lno_cc.thresh_vir = thresh_vir
lno_cc.lo_type = lo_type
lno_cc.no_type = no_type
lno_cc.force_outcore_ao2mo = True

s1e = mf.get_ovlp()
lococc = lno_cc.get_lo(lo_type=lo_type) # localized active occ orbitals
# lococc,locvir = lno_maker.get_lo(lno_cc,lo_type) ### fix this for DF
if eris is None: eris = lno_cc.ao2mo()

frag_lolist = [[i] for i in range(lococc.shape[1])]
nfrag = len(frag_lolist)

frozen_mask = lno_cc.get_frozen_mask()
thresh_pno = [thresh_occ,thresh_vir]
print(f'# lno thresh {thresh_pno}')

if run_frg_list is None:
    run_frg_list = range(nfrag)
    
from jax import random
seeds = random.randint(random.PRNGKey(options["seed"]),
                    shape=(len(run_frg_list),), minval=0, maxval=100*nfrag)

for ifrag in run_frg_list:
    print(f'\n########### running fragment {ifrag+1} ##########')

    fraglo = frag_lolist[ifrag]
    orbfragloc = lococc[:,fraglo]
    THRESH_INTERNAL = 1e-10
    frzfrag, orbfrag, can_orbfrag \
        = lno_maker.make_lno(
            lno_cc,orbfragloc,THRESH_INTERNAL,thresh_pno
            )
    
    mol = mf.mol
    nocc = mol.nelectron // 2 
    nao = mol.nao
    actfrag = np.array([i for i in range(nao) if i not in frzfrag])
    # frzocc = np.array([i for i in range(nocc) if i in frzfrag])
    actocc = np.array([i for i in range(nocc) if i in actfrag])
    actvir = np.array([i for i in range(nocc,nao) if i in actfrag])
    nactocc = len(actocc)
    nactocc = len(actocc)
    nactvir = len(actvir)
    prjlo = orbfragloc.T @ s1e @ orbfrag[:,actocc]

    print(f'# active orbitals: {actfrag}')
    print(f'# active occupied orbitals: {actocc}')
    print(f'# active virtual orbitals: {actvir}')
    print(f'# frozen orbitals: {frzfrag}')

    ecorr_cc,t1,t2 = lno_maker.lno_cc_solver(
                        mf,orbfrag,orbfragloc,frozen=frzfrag,eris=eris
                        )
    ci1 = np.array(t1)
    ci2 = t2 + lib.einsum("ia,jb->ijab",ci1,ci1)
    ci2 = ci2.transpose(0, 2, 1, 3)
    options["seed"] = seeds[ifrag]
    nelec_act = nactocc*2
    norb_act = nactocc+nactvir
    lnoafqmc_runner.prep_lnoafqmc_file(
            mf,orbfrag,options,
            norb_act=norb_act,nelec_act=nelec_act,
            prjlo=prjlo,norb_frozen=frzfrag,
            ci1=ci1,ci2=ci2,chol_cut=1e-10,
            )

lo_type = boys


******** <class 'pyscf.lo.boys.Boys'> ********
conv_tol = 1e-06
conv_tol_grad = None
max_cycle = 100
max_stepsize = 0.01
max_iters = 20
kf_interval = 5
kf_trust_region = 5
ah_start_tol = 1000000000.0
ah_start_cycle = 1
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_max_cycle = 40
ah_trust_region = 3
init_guess = atomic
Set conv_tol_grad to 0.000316228
macro= 1  f(x)= 17.50620794469  delta_f= 17.5062  |g|= 11.5734  1 KF 3 Hx
macro= 2  f(x)= 16.973995464564  delta_f= -0.532212  |g|= 9.88144  1 KF 3 Hx
macro= 3  f(x)= 16.537640307737  delta_f= -0.436355  |g|= 8.29832  1 KF 3 Hx
macro= 4  f(x)= 16.203704505287  delta_f= -0.333936  |g|= 6.59505  1 KF 3 Hx
macro= 5  f(x)= 15.977321235203  delta_f= -0.226383  |g|= 4.79494  1 KF 3 Hx
macro= 6  f(x)= 15.862044509136  delta_f= -0.115277  |g|= 2.92331  1 KF 3 Hx
macro= 7  f(x)= 15.846716469781  delta_f= -0.015328  |g|= 1.0063  1 KF 2 Hx
macro= 8  f(x)= 15.846716444587  delta_f= -2.51942e-08  |g|= 0.00125102  1 KF 2 H

In [ ]:
# fock = mf.get_fock()
# fock_no = orbfrag.T @ fock @ orbfrag
# oo,vv,ov,vo = get_oo_vv_ov_vo(nocc,fock_no)
# print(ov)
# print(vo)

[[-4.49133897e-10  2.76190092e-10 -6.17097255e-10]
 [ 5.98166502e-10  8.66198537e-10  1.21119559e-10]
 [ 2.86028590e-10 -1.96311856e-10  4.04592164e-10]]
[[-4.49133827e-10  5.98166485e-10  2.86028607e-10]
 [ 2.76190107e-10  8.66198577e-10 -1.96311897e-10]
 [-6.17097264e-10  1.21119559e-10  4.04592172e-10]]


In [73]:
from ad_afqmc import config, wavefunctions, stat_utils

ham_data, ham, prop, trial, wave_data, sampler, observable, options, _ = (
    lnoafqmc_runner.prep_lnoafqmc_run())

config.setup_jax()
MPI = config.setup_comm()

# init_time = time.time()
comm = MPI.COMM_WORLD
rank = comm.Get_rank()  # Process rank
size = comm.Get_size()  # Total number of processes


### initialize propagation
seed = options["seed"]
propagator = prop
init_walkers = None
ham_data = wavefunctions.rhf(trial.norb, trial.nelec,n_batch=trial.n_batch
                                )._build_measurement_intermediates(ham_data, wave_data)
ham_data = ham.build_measurement_intermediates(ham_data, trial, wave_data)
ham_data = ham.build_propagation_intermediates(ham_data, propagator, trial, wave_data)
# init_walkers = trial.get_init_walkers(wave_data, prop.n_walkers, restricted=True)
# init_walkers = u.T @ init_walkers
prop_data = propagator.init_prop_data(trial, wave_data, ham_data, init_walkers)

prop_data["key"] = random.PRNGKey(seed + rank)
prop_data["overlaps"] = trial.calc_overlap(prop_data["walkers"], wave_data)
prop_data["n_killed_walkers"] = 0
prop_data["pop_control_ene_shift"] = prop_data["e_estimate"]
print(prop_data['e_estimate'])

# Hostname: yichi-thinkpad
# System Type: Linux
# Machine Type: x86_64
# Processor: x86_64
# Number of MPI ranks: 1
#
# norb: 6
# nelec: (3, 3)
# nchol: 17
#
# n_eql: 4
# n_prop_steps: 10
# n_ene_blocks: 1
# n_sr_blocks: 10
# n_blocks: 10
# n_walkers: 1
# seed: 9
# walker_type: rhf
# trial: cisd
# dt: 0.005
# free_projection: False
# use_gpu: False
# n_exp_terms: 6
# orbital_rotation: True
# do_sr: True
# symmetry: False
# save_walkers: False
# n_batch: 1
# ene0: 0
#
# Hostname: yichi-thinkpad
# System Type: Linux
# Machine Type: x86_64
# Processor: x86_64
-3.0002011843312157


In [74]:
calc_e_rhf = wavefunctions.rhf(trial.norb, trial.nelec,n_batch=trial.n_batch
                                )._calc_energy_restricted
cal_eorb_rhf = wavefunctions.rhf(trial.norb, trial.nelec,n_batch=trial.n_batch
                                )._calc_orbenergy

In [75]:
print(calc_e_rhf(prop_data['walkers'][0],ham_data,wave_data))
print(calc_e_rhf(wave_data['mo_coeff'],ham_data,wave_data))

(-2.748054554358795+0j)
-2.748054554358795


In [ ]:
init_walkers = u.T @ init_walkers

In [77]:
rot_h1,rot_chol = ham_data['rot_h1'],ham_data['rot_chol']
nocc = rot_h1.shape[0]
h_ia = rot_h1[:nocc,nocc:]
veff_ia = 2*jnp.einsum('gia,gjj->ia',rot_chol[:,:nocc,nocc:],rot_chol[:,:nocc,:nocc])\
          - jnp.einsum('gij,gja->ia',rot_chol[:,:nocc,:nocc],rot_chol[:,:nocc,nocc:])
f_ia = h_ia + veff_ia
ham_data['fock_ia'] = f_ia
print(h_ia)
print(veff_ia)
print(f_ia)

[[ 0.09458634 -0.07106406  0.03445047]
 [-0.07101382  0.04517948  0.01641694]
 [ 0.00453721  0.0242948  -0.1416469 ]]
[[-0.08339194  0.07093246 -0.02291779]
 [ 0.05857556 -0.04129798 -0.01365038]
 [-0.01365854 -0.02563307  0.12622045]]
[[ 0.01119441 -0.0001316   0.01153268]
 [-0.01243826  0.0038815   0.00276656]
 [-0.00912133 -0.00133827 -0.01542645]]


In [88]:
prop_data, (blk_en,blk_wt,blk_hf_orb_en,blk_cc_orb_en) \
    = afqmc_maker.block_orb(prop_data,ham_data,prop,trial,wave_data,sampler)
print(blk_en)
# print(walker_rhf_energy1(prop_data['walkers'][0],ham_data,wave_data['mo_coeff']))
print(calc_e_rhf(wave_data['mo_coeff'],ham_data,wave_data))
print(calc_e_rhf(prop_data['walkers'][0],ham_data,wave_data))

-2.9844248786572534
-2.748054554358795
(-2.826554712712941+0.013950506463821455j)


In [80]:
def walker_rhf_efock(walker,ham_data,wave_data):
    '''C_ia <psi|H|psi_i^a}>'''
    trial_mo = wave_data['mo_coeff']
    f_ia = ham_data['fock_ia']
    gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
    gw_ia = gw[:nocc,nocc:]
    e_fock = 2*jnp.einsum('ia,ia->',gw_ia,f_ia)
    return e_fock

def walker_rhf_coexc(walker,ham_data,wave_data):
    '''C_ijab <psi|H|psi_{ia}^{jb}>'''
    rot_h1,rot_chol = ham_data['rot_h1'],ham_data['rot_chol']
    trial_mo = wave_data['mo_coeff']
    nocc = rot_h1.shape[0]
    gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
    f = jnp.einsum('gja,ai->gji',rot_chol[:,:nocc,nocc:],
                    gw.T[nocc:,:nocc],optimize='optimal')
    tr_f = vmap(jnp.trace)(f)
    e_col = 2*jnp.einsum('g,g->',tr_f,tr_f)
    e_exc = -jnp.einsum('gij,gji->',f,f)
    return e_col+e_exc

def walker_rhf_efock_orb(walker,ham_data,wave_data):
    '''C_ia <psi|H|psi_i^a}> don't sum over i'''
    m = jnp.dot(wave_data["prjlo"].T,wave_data["prjlo"])
    f_ia = ham_data['fock_ia']
    trial_mo = wave_data['mo_coeff']
    gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
    gw_ia = gw[:nocc,nocc:]
    e_fock = 2*jnp.einsum('ia,ka,ik->',gw_ia,f_ia,m)
    return e_fock

def walker_rhf_coexc_orb(walker,ham_data,wave_data):
    '''C_ijab <psi|H|psi_{ia}^{jb}> don't sum over i'''
    m = jnp.dot(wave_data["prjlo"].T,wave_data["prjlo"])
    trial_mo = wave_data['mo_coeff']
    rot_h1,rot_chol = ham_data['rot_h1'],ham_data['rot_chol']
    nocc = rot_h1.shape[0]
    gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
    f = jnp.einsum('gja,ai->gji',rot_chol[:,:nocc,nocc:],
                    gw.T[nocc:,:nocc],optimize='optimal')
    tr_f = vmap(jnp.trace)(f)
    e_col = 2*jnp.einsum('gik,ik,g->',f,m,tr_f)
    e_exc = -jnp.einsum('gij,gjk,ik->',f,f,m)
    return e_col+e_exc

def walker_norhf_energy(walker,ham_data,wave_data):
    '''
    C_ia <psi|H|psi_i^a}> + C_ijab <psi|H|psi_{ia}^{jb}> 
    '''
    trial_mo = wave_data['mo_coeff']
    f_ia = ham_data['fock_ia']
    rot_h1,rot_chol = ham_data['rot_h1'],ham_data['rot_chol']
    nocc = rot_h1.shape[0]
    gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
    gw_ia = gw[:nocc,nocc:]
    cg = jnp.einsum('gja,ai->gji',rot_chol[:,:nocc,nocc:],
                    gw_ia.T,optimize='optimal')
    tr_cg = vmap(jnp.trace)(cg)
    e_fock = 2*jnp.einsum('ia,ia->',gw_ia,f_ia)
    e_col = 2*jnp.einsum('g,g->',tr_cg,tr_cg)
    e_exc = -jnp.einsum('gij,gji->',cg,cg)
    e_corr = e_fock+e_col+e_exc
    return e_corr

def walker_norhf_orbenergy(walker,ham_data,wave_data):
    '''
    C_ia <psi|H|psi_i^a}> + C_ijab <psi|H|psi_{ia}^{jb}> 
    don't sum over i
    '''
    m = jnp.dot(wave_data["prjlo"].T,wave_data["prjlo"])
    trial_mo = wave_data['mo_coeff']
    f_ia = ham_data['fock_ia']
    rot_h1,rot_chol = ham_data['rot_h1'],ham_data['rot_chol']
    nocc = rot_h1.shape[0]
    gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
    gw_ia = gw[:nocc,nocc:]
    cg = jnp.einsum('gja,ai->gji',rot_chol[:,:nocc,nocc:],
                    gw_ia.T,optimize='optimal')
    tr_cg = vmap(jnp.trace)(cg)
    e_fock = 2*jnp.einsum('ia,ka,ik->',gw_ia,f_ia,m)
    e_col = 2*jnp.einsum('gik,ik,g->',cg,m,tr_cg)
    e_exc = -jnp.einsum('gij,gjk,ik->',cg,cg,m)
    e_corr = e_fock+e_col+e_exc
    return e_corr

In [ ]:
# trial_mo = wave_data['mo_coeff']
# walker = prop_data['walkers'][0]
# gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
# gw_ia = gw[:nocc,nocc:]
# ef1_frg = 2*jnp.einsum('ia,ia->i',gw_ia,h_ia)
# ef2_frg = 2*jnp.einsum('ia,ia->i',gw_ia,veff_ia)
# ef_frg = 2*jnp.einsum('ia,ia->i',gw_ia,f_ia)
# print(ef1_frg)
# print(ef2_frg)
# print(ef_frg)

[ 0.00346245-0.0195333j  -0.00105026-0.03092344j]
[-0.00346246+0.0195333j   0.00105026+0.03092344j]
[-3.03016742e-11+2.68134730e-10j -4.82261197e-12-4.09286585e-11j]


In [89]:
walker_rhf_efock(prop_data['walkers'][0],ham_data,wave_data)

Array(0.00011039+0.01473282j, dtype=complex128)

In [ ]:
rot_h1, rot_chol = ham_data['rot_h1'],ham_data['rot_chol']
walker = prop_data['walkers'][0]
print(calc_e_rhf(prop_data['walkers'][0],ham_data,wave_data))
print(calc_e_rhf(wave_data['mo_coeff'],ham_data,wave_data)\
      + walker_rhf_coexc(walker,ham_data,wave_data))
print(calc_e_rhf(wave_data['mo_coeff'],ham_data,wave_data)\
      + walker_norhf_energy(walker,ham_data,wave_data))

(-2.826554712712941+0.013950506463821455j)
(-2.826665106615887-0.000782313417585881j)
(-2.8265547127129422+0.013950506463821458j)


In [ ]:
print(calc_e_rhf(prop_data['walkers'][0],ham_data,wave_data))
print(walker_norhf_energy(walker,ham_data,wave_data))
print(mf.e_tot+walker_rhf_coexc(walker,ham_data,wave_data))
print(mf.e_tot+walker_rhf_coexc(walker,ham_data,wave_data)\
      + +walker_rhf_efock(walker,ham_data,wave_data))

(-2.766378475196156-0.0006605576675949715j)
(-2.7663784751954155-0.0006605576675949373j)
(-2.7663784751602916-0.0006605578948010086j)
(-2.766378475195416-0.0006605576675949373j)


In [10]:
trial_mo = wave_data['mo_coeff']
walker = prop_data['walkers'][0]
m = jnp.dot(wave_data["prjlo"].T,wave_data["prjlo"])
gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
f = jnp.einsum('gia,aj->gij',rot_chol[:,:nocc,nocc:],
                gw.T[nocc:,:nocc],optimize='optimal')
# tr_f = vmap(jnp.trace)(f)
tr_chol = vmap(jnp.trace)(rot_chol[:,:nocc,:nocc])
e_fock1 = 2*jnp.einsum('ia,ia->i',gw[:nocc,nocc:],rot_h1[:nocc,nocc:])
e_fock2 = 4*jnp.einsum('gii,g->i',f,tr_chol)\
          - 2*jnp.einsum('gji,gij->i',f,rot_chol[:,:nocc,:nocc])
print(e_fock1)
print(e_fock2)

[0.+0.j 0.+0.j]
[0.+0.j 0.+0.j]


In [ ]:
# walker = prop_data['walkers'][0]
# trial_mo = wave_data['mo_coeff']
# gw = (walker.dot(jnp.linalg.inv(trial_mo.T.conj() @ walker))).T
# gw_ia = gw[:nocc,nocc:]
# print(gw_ia)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [ ]:
# m = jnp.dot(wave_data["prjlo"].T,wave_data["prjlo"])
# print(m)
# jnp.einsum('ia,ka,ik->',gw_ia,f_ia,m)

[[1.23259516e-32 1.11022302e-16]
 [1.11022302e-16 1.00000000e+00]]


In [14]:
ef1 = jnp.einsum('ia,ia->i',gw_ia,h_ia)
ef2 = 2*jnp.einsum('ia,gia,gjj->i',gw_ia,rot_chol[:,:nocc,nocc:],rot_chol[:,:nocc,:nocc])\
      - jnp.einsum('ia,gij,gja->i',gw_ia,rot_chol[:,:nocc,:nocc],rot_chol[:,:nocc,nocc:])

In [131]:
mf.e_tot \
    + walker_norhf_energy(prop_data['walkers'][0],ham_data,wave_data['mo_coeff'])

Array(-4.59433052+0.j, dtype=complex128)

In [62]:
print(walker_rhf_fock_energy(prop_data['walkers'][0],ham_data,wave_data['mo_coeff']))
print(walker_rhf_coexc(prop_data['walkers'][0],ham_data,wave_data['mo_coeff'])[0])

(Array(-2.94908134e-08-2.88966882e-08j, dtype=complex128), Array(-0.00366678-0.07368464j, dtype=complex128), Array(0.00366675+0.07368461j, dtype=complex128))
(-0.05410457269969854+0.005013833702532937j)


In [66]:
mf.e_tot \
    + walker_rhf_coexc(prop_data['walkers'][0],ham_data,wave_data['mo_coeff'])[0] \
    + walker_rhf_fock_energy(prop_data['walkers'][0],ham_data,wave_data['mo_coeff'])[0]

Array(-4.64843512+0.0050138j, dtype=complex128)